### ISSUE TITLE
一点想法

### ISSUE THREAD

**Issue by dragonfly429** [SHERlocked93/wx-updata#1]
1.data的层级不建议太深，不要超过3层，通过优化数据结构和拆分组件实现
2.改层级里面某个属性 用... 方便啊
setData({
    a:{
        ...orginA,
        b:'b',
     }
})

**Comment by SHERlocked93** [comment]
这些都是我平常项目里经常使用的，不过我还是觉得不够方便，所以我才自己写了个工具库，用着感觉很顺手，所以分享给大家，只是提供一个解决方案，如果感觉有用可以试试，我自己是放到生产环境用的
